# Generated by Django 4.1 on 2022-08-12 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': '이미 존재하는 이메일 주소입니다.'}, max_length=254, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=150, verbose_name='비밀번호')),
                ('fullname', models.CharField(max_length=30, verbose_name='이름')),
                ('phone', models.CharField(error_messages={'unique': '이미 존재하는 핸드폰 번호입니다.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='올바른 핸드폰 번호를 입력해주세요.', regex='01[0-9]\\d{3,4}\\d{4}$')], verbose_name='핸드폰번호')),
                ('birthday', models.DateField(verbose_name='생년월일')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('normal', '일반회원'), ('instructor', '강사회원'), ('registered_instructor', '등록강사'), ('responsible_instructor', '책임강사')], default='normal', max_length=30, verbose_name='회원종류')),
                ('license', models.FileField(blank=True, null=True, upload_to='user/license', verbose_name='라이센스')),
                ('kakao', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='kakao id')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정 활성화 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff 권한')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser 권한')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
