# Generated by Django 4.1 on 2022-08-27 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(error_messages={'unique': '이미 존재하는 핸드폰 번호입니다.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='올바른 핸드폰 번호를 입력해주세요.', regex='01[0|1|6|7|8|9]\\d{3,4}\\d{4}$')], verbose_name='핸드폰번호'),
        ),
    ]
