# Generated by Django 4.1 on 2022-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_member_num_user_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_type',
            field=models.CharField(blank=True, choices=[('normal', '일반회원'), ('waiting_instructor_request', '일반회원(강사회원 승인대기)'), ('instructor', '강사회원'), ('registered_instructor', '등록강사'), ('responsible_instructor', '책임강사')], default='일반', max_length=30, verbose_name='가입 유형'),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='가입일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='카카오'),
        ),
        migrations.AlterField(
            model_name='user',
            name='member_num',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='회원번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal', '일반'), ('kakao', '카카오'), ('by_admin', '관리자 생성')], default='normal', max_length=30, verbose_name='회원종류'),
        ),
    ]
