# Generated by Django 4.1 on 2022-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_join_type_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': '이미 존재하는 이메일 주소입니다.'}, max_length=254, null=True, unique=True, verbose_name='이메일'),
        ),
    ]
