# Generated by Django 4.1 on 2022-11-27 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_userlicense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlicense',
            name='license',
        ),
        migrations.AddField(
            model_name='userlicense',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user/license', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='라이센스 이미지'),
        ),
    ]
