# Generated by Django 4.1 on 2022-12-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True, verbose_name='약관 종류')),
                ('title', models.CharField(max_length=60, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
            ],
        ),
    ]
