# Generated by Django 4.1 on 2022-08-17 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.TextField(blank=True, default='', null=True)),
                ('type', models.CharField(blank=True, max_length=10)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productinfo', verbose_name='예약 상품')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_num_of_man', models.IntegerField(default=0, verbose_name='남자 예약자 수')),
                ('total_num_of_woman', models.IntegerField(default=0, verbose_name='여자 예약자 수')),
                ('time', models.TimeField(verbose_name='시간')),
                ('calendar_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_schedule', to='product.reservationcalendar', verbose_name='예약일자')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_man', models.IntegerField(default=0, verbose_name='남자 예약자 수')),
                ('num_of_woman', models.IntegerField(default=0, verbose_name='여자 예약자 수')),
                ('start_time', models.TimeField(verbose_name='예약 시작 시간')),
                ('reservation_at', models.DateTimeField(auto_now_add=True, verbose_name='예약 등록 일자')),
                ('status', models.CharField(choices=[('success', '예약완료'), ('wait_payment', '입금대기'), ('cancel', '예약취소')], max_length=20, verbose_name='예약 상태')),
                ('calendar_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_info', to='product.reservationcalendar', verbose_name='예약 일자')),
                ('product_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productinfo', verbose_name='예약 상품 옵션')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='예약자')),
            ],
        ),
    ]
