# Generated by Django 4.1 on 2022-08-25 14:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIntroduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product/image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='이미지')),
                ('title', models.CharField(max_length=20, verbose_name='상품 제목')),
                ('available_time', models.CharField(max_length=50, verbose_name='이용가능시간')),
                ('description', models.CharField(max_length=500, verbose_name='상품 설명')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.productinfo', verbose_name='상품')),
            ],
        ),
        migrations.CreateModel(
            name='SwimReservationManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='월')),
                ('type', models.CharField(max_length=20, verbose_name='평일/주말')),
                ('total_num_people', models.IntegerField(default=0, verbose_name='총 이용인원')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
