# Generated by Django 4.1 on 2022-08-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productintroduce_swimreservationmanagement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='num_of_man_limit',
            field=models.IntegerField(default=0, verbose_name='남성 인원 제한'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='num_of_woman_limit',
            field=models.IntegerField(default=0, verbose_name='여성 인원 제한'),
        ),
        migrations.AddField(
            model_name='productintroduce',
            name='period',
            field=models.IntegerField(default=4, verbose_name='이용 시간'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='period',
            field=models.IntegerField(default=0, verbose_name='이용 시간'),
        ),
    ]
