# Generated by Django 4.1 on 2022-08-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productinfo_num_of_man_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='예약 번호'),
        ),
    ]
