# Generated by Django 4.1 on 2022-09-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_reservation_reservation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='period',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_schedule',
            field=models.ManyToManyField(to='product.reservationschedule', verbose_name='예약 시간'),
        ),
    ]
