# Generated by Django 4.1 on 2022-11-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_reservation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='예약자 이메일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='fullname',
            field=models.CharField(default='', max_length=20, verbose_name='예약자 이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='핸드폰번호'),
            preserve_default=False,
        ),
    ]
