# Generated by Django 4.1 on 2022-12-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_reservation_memo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='status',
            new_name='reservation_status',
        ),
    ]
