# Generated by Django 4.1 on 2022-12-12 16:33

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_reservation_calendar_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.productinfo'),
        ),
    ]
