# Generated by Django 4.1 on 2022-08-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
            ],
        ),
        migrations.CreateModel(
            name='StaticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='타이틀')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('author', models.CharField(blank=True, max_length=30, null=True, verbose_name='작성자')),
                ('image', models.FileField(blank=True, null=True, upload_to='static/image', verbose_name='이미지')),
                ('static', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticlist.static', verbose_name='스태틱')),
            ],
        ),
        migrations.CreateModel(
            name='StaticItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='링크')),
                ('link_name', models.CharField(max_length=30, verbose_name='링크 이름')),
                ('static_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='staticlist.staticitem', verbose_name='스태틱 아이템')),
            ],
        ),
    ]
