# Generated by Django 4.1 on 2022-11-15 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_reservation_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderID',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_of_man', models.IntegerField(default=0, verbose_name='남성 인원')),
                ('num_of_woman', models.IntegerField(default=0, verbose_name='여성 인원')),
                ('amount', models.IntegerField(verbose_name='가격')),
                ('start_time', models.TimeField(verbose_name='예약 시작 시간')),
                ('raw_data', models.TextField(verbose_name='원본 데이터')),
                ('calendar_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.reservationcalendar', verbose_name='예약 일자')),
                ('product_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productinfo', verbose_name='예약 상품 옵션')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(editable=False, max_length=100, verbose_name='주문 명')),
                ('status', models.CharField(editable=False, max_length=20, verbose_name='결제 상태')),
                ('easy_pay_info', models.TextField(blank=True, editable=False, null=True, verbose_name='이지페이 정보')),
                ('card_info', models.TextField(blank=True, editable=False, null=True, verbose_name='카드 정보')),
                ('requested_at', models.DateTimeField(editable=False, verbose_name='요청일자')),
                ('approved_at', models.DateTimeField(editable=False, verbose_name='승인일자')),
                ('amount', models.IntegerField(editable=False, verbose_name='가격')),
                ('order_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.orderid', verbose_name='결제id')),
                ('reservation', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.reservation', verbose_name='주문 정보')),
            ],
        ),
    ]
