# Generated by Django 4.1 on 2022-12-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_reservation_calendar_date_and_more'),
        ('payment', '0004_alter_paymenthistory_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='reservation',
        ),
        migrations.AddField(
            model_name='orderid',
            name='payment_history',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymenthistory', verbose_name='결제 정보'),
        ),
        migrations.AddField(
            model_name='orderid',
            name='reservation',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.reservation', verbose_name='예약 정보'),
        ),
    ]
