# Generated by Django 4.1 on 2022-08-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal', '일반회원'), ('waiting_instructor_request', '일반회원(강사회원 승인대기)'), ('instructor', '강사회원'), ('registered_instructor', '등록강사'), ('responsible_instructor', '책임강사')], default='normal', max_length=30, verbose_name='회원종류'),
        ),
    ]
