# Generated by Django 4.1 on 2022-11-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_join_type_alter_user_join_date_alter_user_kakao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_type',
            field=models.CharField(blank=True, choices=[('normal', '일반'), ('kakao', '카카오'), ('by_admin', '관리자 생성')], default='일반', max_length=30, verbose_name='가입 유형'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal', '일반회원'), ('waiting_instructor_request', '일반회원(강사회원 승인대기)'), ('instructor', '강사회원'), ('registered_instructor', '등록강사'), ('responsible_instructor', '책임강사')], default='normal', max_length=30, verbose_name='회원종류'),
        ),
    ]
