# Generated by Django 4.1 on 2022-11-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_license_license'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='License',
            new_name='UserLicense',
        ),
    ]
