# Generated by Django 4.1 on 2022-11-27 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_license_userlicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlicense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL, verbose_name='라이센스'),
        ),
    ]
