# Generated by Django 4.1 on 2022-11-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_userlicense_license_userlicense_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instructor_expired_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='강사 만료일자'),
        ),
        migrations.AddField(
            model_name='user',
            name='instructor_register_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='강사 등록일자'),
        ),
    ]
