# Generated by Django 4.1 on 2022-12-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_unique_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='pass 고유 키'),
        ),
    ]
