# Generated by Django 4.1 on 2022-08-17 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_remove_faq_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='신고 시간')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.instructor', verbose_name='게시글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
        ),
        migrations.CreateModel(
            name='InquiryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='신고 시간')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.inquiry', verbose_name='신고자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
        ),
    ]
