# Generated by Django 4.1 on 2022-12-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_rename_content_faq_answer_rename_title_faq_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='첨부파일'),
        ),
    ]
