# Generated by Django 4.1 on 2022-12-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_notice_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='top_fixed',
            field=models.BooleanField(default=False, verbose_name='상단 고정 여부'),
        ),
    ]
