# Generated by Django 4.1 on 2022-12-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_notice_top_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='article/notice', verbose_name='첨부파일'),
        ),
    ]
