# Generated by Django 4.1 on 2022-12-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_alter_notice_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquirycommentreport',
            name='target',
        ),
        migrations.RemoveField(
            model_name='inquirycommentreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='is_solved',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='answer',
            field=models.TextField(default=0, verbose_name='답변'),
        ),
        migrations.DeleteModel(
            name='InquiryComment',
        ),
        migrations.DeleteModel(
            name='InquiryCommentReport',
        ),
    ]
