# Generated by Django 4.1 on 2022-08-11 11:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='제목')),
                ('content', models.TextField(verbose_name='게시글 본문')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='제목')),
                ('content', models.TextField(verbose_name='게시글 본문')),
                ('is_resolve', models.BooleanField(default=False, verbose_name='해결여부')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='제목')),
                ('content', models.TextField(verbose_name='게시글 본문')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='제목')),
                ('content', ckeditor.fields.RichTextField(verbose_name='게시글 본문')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='댓글 내용')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.instructor', verbose_name='게시글')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='article/instructor', verbose_name='첨부파일')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.instructor', verbose_name='게시글')),
            ],
        ),
        migrations.CreateModel(
            name='InquiryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='댓글 내용')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.instructor', verbose_name='게시글')),
            ],
        ),
        migrations.CreateModel(
            name='InquiryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='article/instructor', verbose_name='첨부파일')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.instructor', verbose_name='게시글')),
            ],
        ),
    ]
