# Generated by Django 4.1 on 2022-08-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_faq_created_inquiry_author_inquiry_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryattachment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.inquiry', verbose_name='게시글'),
        ),
        migrations.AlterField(
            model_name='inquirycomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.inquiry', verbose_name='게시글'),
        ),
    ]
