# Generated by Django 4.1 on 2022-08-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_inquiryattachment_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='created',
        ),
    ]
