# Generated by Django 4.1 on 2022-08-18 17:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_instructorreport_inquiryreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='is_resolve',
            new_name='is_solved',
        ),
        migrations.AlterField(
            model_name='inquiryattachment',
            name='attachment',
            field=models.FileField(upload_to='article/inquiry', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='첨부파일'),
        ),
        migrations.AlterField(
            model_name='inquiryreport',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.inquiry', verbose_name='게시글'),
        ),
        migrations.AlterField(
            model_name='instructorattachment',
            name='attachment',
            field=models.FileField(upload_to='article/instructor', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='첨부파일'),
        ),
    ]
