# Generated by Django 4.1 on 2022-12-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_rename_is_resolve_inquiry_is_solved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='공개 여부'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='공개 여부'),
        ),
    ]
