# Generated by Django 4.1 on 2022-12-03 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0007_inquiry_is_visible_instructor_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiryreport',
            old_name='inquiry',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='instructorreport',
            old_name='instructor',
            new_name='target',
        ),
        migrations.CreateModel(
            name='InstructorCommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='신고 시간')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.instructorcomment', verbose_name='게시글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
        ),
        migrations.CreateModel(
            name='InquiryCommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='신고 시간')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.inquirycomment', verbose_name='게시글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
        ),
    ]
