# Generated by Django 4.1 on 2022-12-04 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_rename_inquiry_inquiryreport_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='작성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0, verbose_name='순서'),
        ),
        migrations.AddField(
            model_name='notice',
            name='top_fixed',
            field=models.BooleanField(default=False, verbose_name='상단 고정'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='content',
            field=models.TextField(verbose_name='답변'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=60, verbose_name='질문'),
        ),
    ]
