# Generated by Django 4.1 on 2022-12-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_faq_created_faq_order_notice_top_fixed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='content',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title',
            new_name='question',
        ),
    ]
