# Generated by Django 4.1 on 2022-12-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_remove_inquirycommentreport_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='answer',
            field=models.TextField(default='', verbose_name='답변'),
        ),
    ]
