# Generated by Django 4.1 on 2022-11-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_reservation_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='가격'),
            preserve_default=False,
        ),
    ]
