# Generated by Django 4.1 on 2022-12-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_reservation_email_reservation_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='메모'),
        ),
    ]
