# Generated by Django 4.1 on 2022-12-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_status_reservation_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='calendar_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_info', to='product.reservationcalendar', verbose_name='이용 날짜'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_schedule',
            field=models.ManyToManyField(to='product.reservationschedule', verbose_name='이용 시간'),
        ),
    ]
