"""
Django settings for theme project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--xt@b&l*dwdf(23+bsoit1id%28mgft^-ef#wis4vcs+0^4ll!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # libraries
    'rest_framework',
    'ckeditor',
    'drf_yasg',
    'mptt',
    'django_mptt_admin',
    'django_apscheduler',
    
    # user apps
    'account',
    'product',
    'fileserver',
    'payment',
    'staticlist',
    # 'custom_admin',
    # 'scheduler',
]

APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"  # Default

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'theme.middleware.ResponseFormattingMiddleware',
]
if DEBUG:
    MIDDLEWARE.append('theme.middleware.RequestLogMiddleware')

ROOT_URLCONF = 'theme.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'theme.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True
USE_L10N = True

USE_TZ = True

MEDIA_URL = 'api/fileserver/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = "account.User"
    
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated'
        'theme.permissions.IsAuthenticated'
    ],
    
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ],
    
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_PAGINATION_CLASS': 'theme.pagination.PageNumberPagination',
    'PAGE_SIZE': 10, 
}

LOGIN_URL = '/admin/login/'

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization'
        }
    },
    
    # 'OPERATIONS_SORTER': 'alpha', # alpha or method
    # 'TAGS_SORTER': False, # False or alpha
    'DOC_EXPANSION': False, # False or list or full
    # 'LOGIN_URL': '/admin/login/',
    'DEFAULT_MODEL_RENDERING': 'example', # model or example
    'LOGOUT_URL': '/admin/logout/',
    'USE_SESSION_AUTH': True,
}

KAKAO_LOGIN_URI = "https://kauth.kakao.com/oauth/authorize"
KAKAO_TOKEN_URI = "https://kauth.kakao.com/oauth/token"
KAKAO_PROFILE_URI = "https://kapi.kakao.com/v2/user/me"

KAKAO_REDIRECT_URI = "http://localhost:8000/api/user/kakao/login/callback/"
KAKAO_REST_API_KEY = "c2ad060af57eb36f867a5c3db856a7ab" # chlee dev
KAKAO_CLIENT_SECRET_KEY = "eE960C1Sr1x96EPGpFeNXymCrL8FeJaT" # chlee dev

# https://docs.tosspayments.com/reference/test/v1/payments/confirm/POST

if DEBUG: # dev
    TOSS_SECRET_KEY_BASE64 = "dGVzdF9za19LbWE2MFJaYmxycTFaTkJuTFJyd3pZV0JuMTRNOg=="
    TOSS_SECRET_KEY = "test_sk_Kma60RZblrq1ZNBnLRrwzYWBn14M" # dev
else:
    TOSS_SECRET_KEY_BASE64 = "dGVzdF9za19LbWE2MFJaYmxycTFaTkJuTFJyd3pZV0JuMTRNOg=="
    TOSS_SECRET_KEY = "test_sk_Kma60RZblrq1ZNBnLRrwzYWBn14M"

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'ch.lee@among.software' # chlee dev
EMAIL_HOST_PASSWORD = 'vqpsrveurjlfljus' # chlee dev

EMAIL_USE_TLS = True

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

CSRF_TRUSTED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000", "https://www.t-sports.kr", ]
CORS_ORIGIN_WHITELIST = CSRF_TRUSTED_ORIGINS

NUM_OF_SWIM_LIMIT = 40 # 일반수영 인원제한
THEME_START_TIME = 7 # 영업 시작 시간
THEME_END_TIME = 19 # 영업 종료 시간, 24 이상 설정 시 에러가 발생 할 수 있음

# show sql querys
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#         }
#     },
#     'loggers': {
#         'django.db.backends': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#     }
# }