# Generated by Django 4.1 on 2022-11-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderid',
            name='raw_data',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='raw_data',
            field=models.TextField(default='', verbose_name='원본 데이터'),
            preserve_default=False,
        ),
    ]
