# Generated by Django 4.1 on 2022-11-15 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_orderid_raw_data_paymenthistory_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderid',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='예약자 이메일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderid',
            name='fullname',
            field=models.CharField(default='', max_length=20, verbose_name='예약자 이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderid',
            name='phone',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid', message='올바른 핸드폰 번호를 입력해주세요.', regex='01[0|1|6|7|8|9]\\d{3,4}\\d{4}$')], verbose_name='핸드폰번호'),
            preserve_default=False,
        ),
    ]
