# Generated by Django 4.1 on 2022-12-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_orderid_email_orderid_fullname_orderid_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='order_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.orderid', verbose_name='청구 정보'),
        ),
    ]
